# Generated by Django 4.2.10 on 2024-02-16 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forklift', '0002_alter_tracker_device_driver_and_more'),
        ('deviceData', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GPS_Data',
            new_name='GPSData',
        ),
    ]
