# Generated by Django 4.2.10 on 2024-02-16 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forklift', '0002_alter_tracker_device_driver_and_more'),
        ('deviceData', '0002_rename_gps_data_gpsdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpsdata',
            name='device_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imei_id', to='forklift.tracker_device'),
        ),
        migrations.CreateModel(
            name='RAWData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_time', models.DateTimeField()),
                ('data_length', models.IntegerField()),
                ('data', models.CharField(max_length=4096)),
                ('device_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forklift.tracker_device')),
            ],
        ),
    ]
