# Generated by Django 4.2.10 on 2024-02-16 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forklift', '0002_alter_tracker_device_driver_and_more'),
        ('deviceData', '0003_alter_gpsdata_device_id_rawdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='EXTData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_date', models.DateField(auto_now_add=True)),
                ('server_time', models.TimeField(auto_now_add=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('speed', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('distance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('batt_voltage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('batt_amp', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('batt_capacity', models.IntegerField()),
                ('batt_power', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('watt_hr', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('device_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forklift.tracker_device')),
            ],
        ),
    ]
