# Generated by Django 4.2.10 on 2024-02-16 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deviceData', '0004_extdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawdata',
            name='device_id',
            field=models.CharField(max_length=15),
        ),
    ]
