# Generated by Django 4.2.10 on 2024-02-16 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deviceData', '0005_alter_rawdata_device_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpsdata',
            name='latitude',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='gpsdata',
            name='longitude',
            field=models.IntegerField(),
        ),
    ]
