# Generated by Django 4.2.10 on 2024-02-17 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deviceData', '0006_alter_gpsdata_latitude_alter_gpsdata_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpsdata',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='gpsdata',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
