# Generated by Django 4.2.10 on 2024-02-22 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deviceData', '0007_alter_gpsdata_latitude_alter_gpsdata_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpsdata',
            name='gsmAreaCode',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gpsdata',
            name='gsmOperatorCode',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gpsdata',
            name='gsmSignal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gpsdata',
            name='ignition',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='gpsdata',
            name='movementState',
            field=models.BooleanField(default=0),
        ),
    ]
