# Generated by Django 4.2.10 on 2024-02-22 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deviceData', '0008_gpsdata_gsmareacode_gpsdata_gsmoperatorcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpsdata',
            name='odometer',
            field=models.IntegerField(default=0),
        ),
    ]
