# Generated by Django 4.2.10 on 2024-02-22 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deviceData', '0009_gpsdata_odometer'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpsdata',
            name='satilite',
            field=models.IntegerField(default=0),
        ),
    ]
