# Generated by Django 4.2.10 on 2024-02-22 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deviceData', '0010_gpsdata_satilite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gpsdata',
            old_name='satilite',
            new_name='satellite',
        ),
    ]
