# Generated by Django 4.2.10 on 2024-03-23 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deviceData', '0011_rename_satilite_gpsdata_satellite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpsdata',
            name='state',
            field=models.IntegerField(choices=[(1, 'Inactive'), (2, 'Idle'), (3, 'Active'), (4, 'Alert')]),
        ),
    ]
