# Generated by Django 4.2.10 on 2024-02-16 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forklift', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker_device',
            name='driver',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='tracker_device',
            name='vehicle_name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
