# Generated by Django 4.2.10 on 2024-02-16 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forklift', '0002_alter_tracker_device_driver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker_device',
            name='hardware_version',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='tracker_device',
            name='manufracture',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='tracker_device',
            name='software_version',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
