# Generated by Django 4.2.10 on 2024-02-16 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forklift', '0003_tracker_device_hardware_version_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tracker_device',
            old_name='manufracture',
            new_name='manufacturer',
        ),
    ]
